# Generated by Django 5.1 on 2024-09-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
